spring:
  config:
    activate:
      on-profile: "prod"


build:
  version: "1.O"


accounts:
  message: "Welcome to Prod API's"
  contactDetails:
    name: "Rocky"
    email: "Rocky@gmail.com"
  onCallSupport:
    -(234) 6343-1234
    -(534) 3232-5678
